manifest_version = 1

[package]
name = "example-cs-component"
version = "1.0.0"

wit-world-version = "0.3.0"

[package.build]
command = "dotnet build"
output_path = "./bin/Debug/net9.0/wasi-wasm/publish/example-cs-component.wasm"
