manifest-version = 1

[component]
name = "example-cs-component"
version = "1.0.0"
category = "data-collection"
subcategory = "analytics"
description = "Example CSharp component for data collection"
documentation = "https://github.com/edgee-cloud/example-cs-component"
repository = "https://github.com/edgee-cloud/example-cs-component"
wit-world-version = "0.4.0"

[component.build]
command = "dotnet build && ls -lRa ./bin/Debug/net9.0/wasi-wasm/ && mv ./bin/Debug/net9.0/wasi-wasm/publish/example-cs-component.wasm ./dc-component.wasm"
output_path = "./dc-component.wasm"

[component.settings.example]
title = "Example Config Field"
type = "string"
