manifest_version = 1

[package]
name = "example-cs-component"
version = "1.0.0"

wit-world-version = "0.4.0"

[package.build]
command = "dotnet build && mv ./bin/Debug/net9.0/wasi-wasm/publish/example-cs-component.wasm ./dc-component.wasm"
output_path = "./dc-component.wasm"
