manifest-version = 1

[component]
name = "example-cs-component"
version = "1.0.0"
category = "data-collection"
subcategory = "analytics"
description = "Example CSharp component for data collection"
documentation = "https://github.com/edgee-cloud/example-cs-component"
repository = "https://github.com/edgee-cloud/example-cs-component"
language = "CSharp"
wit-version = "0.5.0"

[component.build]
command = "dotnet build &&  mv ./bin/Debug/net9.0/wasi-wasm/publish/example-cs-component.wasm ./dc_component.wasm"
output_path = "./dc_component.wasm"

[component.settings.example]
title = "Example Config Field"
type = "string"
